serviceInstance:
  nameOverride: warehouse-service
  image:
    repository: tyku/hw_distributed_transaction
    imagePullPolicy: Always
    tag: latest
  containerPort: 8000
  service:
    type: ClusterIP
    port: 80
