serviceInstance:
  nameOverride: payment-service
  image:
    repository: tyku/hw-distributed-transaction
    imagePullPolicy: Always
    tag: latest
  containerPort: 8000
  service:
    type: ClusterIP
    port: 80
